@Auth0Maui.UserServices_HostAddress = http://localhost:5226

GET {{Auth0Maui.UserServices_HostAddress}}/todos/
Accept: application/json

###

GET {{Auth0Maui.UserServices_HostAddress}}/todos/1
Accept: application/json

###
